In [1]:
#Proprietary content. © Great Learning. All Rights Reserved. Unauthorized use or distribution prohibited.

# Deep learning examples using Keras + Tensorflow

## Build first network using Keras

In [1]:
# Create simple network with Keras
from keras.models import Sequential
from keras.layers import Dense
import numpy

# load pima indians dataset
dataset = numpy.loadtxt("pima-indians-diabetes.csv", delimiter=",")
print(dataset.shape)
# split into input (X) and output (Y) variables
X = dataset[:,0:8]
Y = dataset[:,8]
print(X.shape)
print(Y.shape)


C:\WinPython-64bit-3.5.3.0Qt5\python-3.5.3.amd64\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


(768, 9)
(768, 8)
(768,)


In [2]:
# create first model
model = Sequential()
#Adding 3 dense layers
model.add(Dense(12, input_dim=8,init='uniform'))
model.add(Dense(8,init='uniform'))
model.add(Dense(1,init='uniform'))
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
# Fit the model
model.fit(X, Y, nb_epoch=20, batch_size=10,  verbose=2)
# evaluate the model

scores = model.evaluate(X, Y)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

C:\WinPython-64bit-3.5.3.0Qt5\python-3.5.3.amd64\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(12, kernel_initializer="uniform", input_dim=8)`
C:\WinPython-64bit-3.5.3.0Qt5\python-3.5.3.amd64\lib\site-packages\ipykernel\__main__.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(8, kernel_initializer="uniform")`
C:\WinPython-64bit-3.5.3.0Qt5\python-3.5.3.amd64\lib\site-packages\ipykernel\__main__.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1, kernel_initializer="uniform")`


TypeError: sigmoid_cross_entropy_with_logits() got an unexpected keyword argument 'labels'

In [12]:
# Extending the first model with activation functions
model = Sequential()
#specifying activation functions
model.add(Dense(3, input_dim=8, init='uniform', activation='relu'))
#model.add(Dense(8, init='uniform', activation='relu'))
model.add(Dense(1, init='uniform', activation='sigmoid'))
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
# Fit the model
model.fit(X, Y, nb_epoch=20, batch_size=10,  verbose=2)
# evaluate the model
scores = model.evaluate(X, Y)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

Epoch 1/20
0s - loss: 0.6767 - acc: 0.6107
Epoch 2/20
0s - loss: 0.6678 - acc: 0.6510
Epoch 3/20
0s - loss: 0.6607 - acc: 0.6576
Epoch 4/20
0s - loss: 0.6577 - acc: 0.6549
Epoch 5/20
0s - loss: 0.6534 - acc: 0.6510
Epoch 6/20
0s - loss: 0.6501 - acc: 0.6549
Epoch 7/20
0s - loss: 0.6441 - acc: 0.6602
Epoch 8/20
0s - loss: 0.6396 - acc: 0.6589
Epoch 9/20
0s - loss: 0.6334 - acc: 0.6576
Epoch 10/20
0s - loss: 0.6295 - acc: 0.6680
Epoch 11/20
0s - loss: 0.6222 - acc: 0.6628
Epoch 12/20
0s - loss: 0.6190 - acc: 0.6693
Epoch 13/20
0s - loss: 0.6123 - acc: 0.6784
Epoch 14/20
0s - loss: 0.6082 - acc: 0.6784
Epoch 15/20
0s - loss: 0.6023 - acc: 0.6823
Epoch 16/20
0s - loss: 0.5983 - acc: 0.6875
Epoch 17/20
0s - loss: 0.5957 - acc: 0.6992
Epoch 18/20
0s - loss: 0.6001 - acc: 0.6888
Epoch 19/20
0s - loss: 0.5946 - acc: 0.6862
Epoch 20/20
0s - loss: 0.5910 - acc: 0.7031
704/768 [==========================>...] - ETA: 0s

In [13]:
# evaluate the model
scores = model.evaluate(X, Y)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

512/768 [===================>..........] - ETA: 0sacc: 69.14%


In [14]:
model.summary()

____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
dense_7 (Dense)                  (None, 3)             27          dense_input_3[0][0]              
____________________________________________________________________________________________________
dense_8 (Dense)                  (None, 1)             4           dense_7[0][0]                    
Total params: 31
Trainable params: 31
Non-trainable params: 0
____________________________________________________________________________________________________


In [15]:
for layer in model.layers:
    print(layer.name, layer.inbound_nodes, layer.outbound_nodes)

dense_7 [<keras.engine.topology.Node object at 0x0000016F88549128>] [<keras.engine.topology.Node object at 0x0000016F89E75C88>]
dense_8 [<keras.engine.topology.Node object at 0x0000016F89E75C88>] []


In [16]:
model.get_weights()

[array([[ 0.0367197 ,  0.32576466, -0.30563745],
        [-0.03054102,  0.07326576, -0.07535113],
        [-0.03221828, -0.09496181,  0.20233087],
        [ 0.00759904,  0.0486616 ,  0.02355786],
        [-0.01241106,  0.06141287,  0.03117285],
        [-0.02536973, -0.03432333,  0.01945392],
        [-0.04839655,  0.05393013, -0.18624373],
        [ 0.0280936 ,  0.03104304, -0.03765763]], dtype=float32),
 array([-0.00837211, -0.3715317 ,  0.43919215], dtype=float32),
 array([[ 0.00248669],
        [ 0.07798002],
        [-0.15298077]], dtype=float32),
 array([-0.32388037], dtype=float32)]

In [17]:
# Multilayer Perceptron
from keras.utils import plot_model
# plot graph
plot_model(model, to_file='multilayer_perceptron_graph.png')


ImportError: cannot import name 'plot_model'

In [ ]:
# calculate predictions
predictions = model.predict(X)
# round predictions
rounded = [round(x[0]) for x in predictions]
print(predictions)
print(rounded)

# Second Keras example


In [ ]:
'''Trains and evaluate a simple MLP on the Reuters newswire topic classification task.'''

from __future__ import print_function
import numpy as np
np.random.seed(1337)  # for reproducibility

from keras.datasets import reuters
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.utils import np_utils
from keras.preprocessing.text import Tokenizer

#define parameters
max_words = 1000
batch_size = 32
nb_epoch = 5
#Load data
print('Loading data...')
(X_train, y_train), (X_test, y_test) = reuters.load_data(nb_words=max_words, test_split=0.2)
print(len(X_train), 'train sequences')
print(len(X_test), 'test sequences')
#Number of classes
nb_classes = np.max(y_train)+1
print(nb_classes, 'classes')

#Vectorize the data
print('Vectorizing sequence data...')
tokenizer = Tokenizer(nb_words=max_words)
X_train = tokenizer.sequences_to_matrix(X_train, mode='binary')
X_test = tokenizer.sequences_to_matrix(X_test, mode='binary')
print('X_train shape:', X_train.shape)
print('X_test shape:', X_test.shape)

print('Convert class vector to binary class matrix (for use with categorical_crossentropy)')
Y_train = np_utils.to_categorical(y_train, nb_classes)
Y_test = np_utils.to_categorical(y_test, nb_classes)
print('Y_train shape:', Y_train.shape)
print('Y_test shape:', Y_test.shape)


In [ ]:
#Build the model
print('Building model...')
model = Sequential()
model.add(Dense(512, input_shape=(max_words,)))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(nb_classes))
model.add(Activation('softmax'))
#compile the model
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              )
#Fit the model with the training data
history = model.fit(X_train, Y_train,
                    nb_epoch=nb_epoch, batch_size=batch_size,
                    verbose=1, validation_split=0.1)
#evaluate the model
score = model.evaluate(X_test, Y_test,
                       batch_size=batch_size, verbose=1)
print('Test score:', score)
print('Test accuracy:', score)